version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: api_user
      POSTGRES_PASSWORD: De1tY0urM0m
      POSTGRES_DB: insurancedb
    ports:
      - "5432:5432"
